# Copyright 2020 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# See https://www.pantsbuild.org/docs/using-pants-in-ci.

[GLOBAL]
dynamic_ui = false
colors = true

# Set to `true` if you have a Pants remote cache provider available for CI builds
remote_cache_read = false
remote_cache_write = false

[pytest]
args = ["-vv", "--no-header"]

