name: Make patch release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
    - name: Check out master
      uses: actions/checkout@v2
      with:
        ref: master
        persist-credentials: false
        fetch-depth: 0
    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.11
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run style check
      run: make lint
    - name: Run Scala tests
      run: sbt test
      env:
        SPARK_LOCAL_IP: "127.0.0.1"
    - name: Install jar for Python tests
      run: sbt publishLocal
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Pip install
      working-directory: python
      run: |
        sudo apt-get -y -qq install libsnappy-dev ffmpeg
        python -m pip install -e .[all,dev]
    - name: Python lint
      working-directory: python
      run: pylint rikai || true
    - name: Run python tests
      working-directory: python
      run: |
        pytest -v --durations=10 --ignore=tests/parquet/internal
      env:
        SPARK_LOCAL_IP: "127.0.0.1"
    - name: Bump version and make tag
      run: make release
    - name: Push new version and tag
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
        tags: true
    - name: Make new github release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Bump patch back to dev build
      run: make patch
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
