name: Experimental

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  torchhub:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: sbt install
        run: |
          sbt publishLocal
      - name: Install Dependencies
        working-directory: python
        run: |
          python -m pip install -q . wheel
      - name: Install rikai-torchhub
        working-directory: experimental/torchhub
        run: |
          python -m pip install .[dev]
      - name: Test rikai-torchhub
        working-directory: experimental/torchhub
        run: pytest -s -o log_cli=true
  tfhub:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: sbt install
        run: |
          sbt publishLocal
      - name: Install Dependencies
        working-directory: python
        run: |
          python -m pip install -q . wheel
      - name: Install rikai-tfhub
        working-directory: experimental/tfhub
        run: |
          python -m pip install .[dev]
      - name: Test rikai-tfhub
        working-directory: experimental/tfhub
        run: pytest -s -o log_cli=true

