name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  formatcheck:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Make Lint
        run: |
          pip install isort black pylint pycodestyle flake8
          make lint
      - name: Python lint
        working-directory: python
        run: pylint rikai || true
